- name: install nginx server
  ansible.builtin.dnf:
    name: nginx
    state: installed

- name: enable and start nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: include common role tasks
  ansible.builtin.include_role:
    name: common
    tasks_from: main.yaml # if we do not specify tasks_from it will take default main.yaml. if we have multiple task files we can specify here

# - name: delete html directory
#   ansible.builtin.file:
#     path: /usr/share/nginx/html
#     state: absent # delete directory if exists

# - name: create html directory
#   ansible.builtin.file:
#     path: /usr/share/nginx/html
#     state: directory

# - name: download frontend code
#   ansible.builtin.get_url:
#     url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
#     dest: /tmp/frontend.zip

# - name: unzip frontend code
#   ansible.builtin.unarchive:
#     src: /tmp/frontend.zip
#     dest: /usr/share/nginx/html
#     remote_src: yes

- name: copy expense config
  ansible.builtin.template:
    src: expense.conf.j2
    dest: /etc/nginx/default.d/expense.conf
  notify:
    - Restart nginx # notify is used to trigger handler
